### ISSUE TITLE
The live tool doesn't appear to work? Can you provide working examples?

### ISSUE THREAD

**Issue by sean-ww** [Vizrex/MySQL-to-Laravel-Migrations#1]
For example, why doesn't this work?
```
CREATE TABLE attendance_statuses (attendance_status_id int(11) NOT NULL, name varchar(64) NOT NULL);
```

**Comment by zeshanfarooqi** [comment]
**The issue has been fixed!**
Someone used this tool last time and generated tables with some special characters. The `DROP TABLE `statement didn't have the enclosed table name. It is now enclosed in backtick (`) so issue has been resolved. Code has also been updated on live link. Have a look: http://vizrex.com/tools/mysql-to-laravel
