### ISSUE TITLE
Useless Demo

### ISSUE THREAD

**Issue by wowcut** [Vizrex/MySQL-to-Laravel-Migrations#2]
The Demo instance is useless, it just shows a default Laravel instance - there is no hint about how to use your tool. If one should just login to see anything, please add at least one line of description to your readme saying it, e.g. "Check out the demo instance by logging in with admin/admin". 

Also some description what features this tool provide would be very nice, and of course wthout documentation you do not even need to start publishing anything at all. ATM it is very hard to recognize that you are committed to quality. Hint: yes, potential customers are checking your code repos and it is **very** important how this place is looking.

**Comment by zeshanfarooqi** [comment]
There is a link to register on page that you've mentioned. This tool is intended for Laravel developers only who are well familiar with conventions and the typical layout of landing page as well. The registration is extremely simple and totally free.

If you think there needs to be some improvement, please feel free to contribute!
